version: '2'
services:
  email:
    image: theypsilon/docker-fakesmtp
    container_name: email
  db:
    image: trondheimdc/ems-postgresql
    container_name: ems-postgres
  ems-app:
    image: trondheimdc/ems
    container_name: ems
    depends_on:
      - db
    #ports:
    #      - "5006:5005"
    env_file:
      - ems-variables.env
  submitit-app:
    image: trondheimdc/submitit
    container_name: submitit
    ports: 
      - "8080:8080"
      #- "5007:5005"
    env_file:
      - submitit-variables.env
    depends_on:
      - ems-app
      - email
  cake-app:
    image: trondheimdc/cake
    container_name: cake
    ports:
      - "8082:8082"
    env_file:
          - cake-variables.env
    depends_on:
      - ems-app
      - email
    dns: 8.8.8.8
  api-app:
    image: trondheimdc/api
    container_name: api
    ports:
      - "8083:8083"
    depends_on:
      - ems-app
networks:
   default:
     driver: bridge
     driver_opts:
       'com.docker.network.enable_ipv6': 'true'
