version: '3'
services:
  email:
    image: theypsilon/docker-fakesmtp
    container_name: email
    expose:
      - 25
    networks:
      - tdcnet
  db:
    image: trondheimdc/tdc-postgresql
    container_name: tdc-postgres
    volumes:
      - psqldata:/var/lib/postgresql/data
      - psqldata:/home/postgres
    restart: unless-stopped
    networks:
      - tdcnet
  sleepingpill-app:
    image: trondheimdc/sleepingpillcore
    container_name: sleepingpill
    depends_on:
      - db
    ports:
      - "8080:8083"
      - "5005:5005"
    env_file:
      - sleepingpillcore-variables.env
    restart: unless-stopped
    networks:
      - tdcnet
volumes:
  psqldata:
    driver: local
networks:
  tdcnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.enable_ipv6: "true"