version: '2'
services:
  email:
    image: theypsilon/docker-fakesmtp
    container_name: email
  db:
    image: trondheimdc/ems-postgresql
    container_name: ems-postgres
  ems-app:
    image: trondheimdc/ems
    container_name: ems
    depends_on:
      - db
  submitit-app:
    image: trondheimdc/submitit
    container_name: submitit
    ports: 
      - "8080:8080"
    env_file:
      - submitit-variables.env
    depends_on:
      - ems-app
      - email
  cake-app:
    image: trondheimdc/cake
    container_name: cake
    ports:
      - "8082:8082"
    env_file:
          - cake-variables.env
    depends_on:
      - ems-app
      - email
  api-app:
    image: trondheimdc/api
    container_name: api
    ports:
      - "8083:8083"
    depends_on:
      - ems-app
