version: '2'
services:
  #email:
  #  image: theypsilon/docker-fakesmtp
  #  container_name: email
  db:
    image: trondheimdc/ems-postgresql
    container_name: ems-postgres
    volumes:
      - psqldata:/var/lib/postgresql
    restart: unless-stopped
  ems-app:
    image: trondheimdc/ems
    container_name: ems
    depends_on:
      - db
    #ports:
    #  - "5005:5005"
    env_file:
      - ems-variables.env
    restart: unless-stopped
  devnull-app:
    image: trondheimdc/devnull
    container_name: devnull
    depends_on:
      - db
      - ems-app
    ports:
      - "8084:8084"
    env_file:
      - devnull-variables.env
    restart: unless-stopped
  submitit-app:
    image: trondheimdc/submitit
    container_name: submitit
    ports:
      - "8080:8080"
    #  - "5006:5005"
    env_file:
      - submitit-variables.env
    depends_on:
      - ems-app
      - email
    restart: unless-stopped
  cake-app:
    image: trondheimdc/cake
    container_name: cake
    ports:
      - "8082:8082"
    #  - "5007:5005"

    env_file:
       - cake-variables.env
    depends_on:
      - ems-app
      - email
    dns: 8.8.8.8
    restart: unless-stopped
  api-app:
    image: trondheimdc/api
    container_name: api
    ports:
      - "8083:8083"
    env_file:
      - api-variables.env
    depends_on:
      - ems-app
    restart: unless-stopped
networks:
   default:
     driver: bridge
     driver_opts:
       'com.docker.network.enable_ipv6': 'true'
volumes:
  psqldata:
    driver: local
