version: '3'
services:
  tdc-email:
    image: theypsilon/docker-fakesmtp
    container_name: tdc-email
    expose:
      - 25
    networks:
      - tdcnet
  tdc-db:
    image: trondheimdc/tdc-postgresql
    container_name: tdc-postgres
    volumes:
      - tdc-psqldata:/var/lib/postgresql/data
      - tdc-psqldata:/home/postgres
    restart: unless-stopped
    networks:
      - tdcnet
  tdc-sleepingpill-app:
    image: trondheimdc/sleepingpillcore
    container_name: tdc-sleepingpill
    depends_on:
      - tdc-db
    volumes:
      - ./sleepingpill/sleepingPill.conf:/sleepingPill.conf
    ports:
      - "8082:8082"
        #      - "5005:5005"
    env_file:
      - sleepingpillcore-variables.env
    restart: unless-stopped
    networks:
      - tdcnet
  tdc-submit-backend-app:
    image: trondheimdc/submit-backend
    container_name: tdc-submit-backend
    ports:
      - "8080:8081"
        #      - "5008:5005"
    env_file:
      - submit-backend-variables.env
    depends_on:
      - tdc-sleepingpill-app
      - tdc-email
    volumes:
      - ./submit/submit-backend.properties:/submit-backend.properties
    restart: unless-stopped
    networks:
      - tdcnet
  tdc-submit-frontend-app:
    image: trondheimdc/submit-frontend
    container_name: tdc-submit-frontend
    ports:
      - "8085:80"
    depends_on:
      - tdc-submit-backend-app
    volumes:
      - ./submit/nginx.conf:/etc/nginx/sites-enabled/default
    restart: unless-stopped
    networks:
      - tdcnet
  tdc-devnull-app:
    image: trondheimdc/devnull
    container_name: tdc-devnull
    depends_on:
      - tdc-db
      - tdc-sleepingpill-app
    ports:
      - "8084:5432"
#      - "5009:5005"
    env_file:
      - devnull-variables.env
    restart: unless-stopped
    networks:
      - tdcnet
  tdc-cake-app:
    image: trondheimdc/cake
    container_name: tdc-cake
    ports:
      - "8083:8082"
        #      - "5007:5005"
    env_file:
       - cake-variables.env
    depends_on:
      - tdc-sleepingpill-app
      - tdc-email
    restart: unless-stopped
    networks:
      - tdcnet
volumes:
  tdc-psqldata:
    driver: local
networks:
  tdcnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.enable_ipv6: "true"
